Openassetsj
chaintope/openassetsj pull request #3
Opened 2018-06-13 10:24 UTC by purabparekh

Code to generate issuance transaction

2018-06-14 01:11 UTC, azuchi commented on src/main/java/com/chaintope/openassetsj/OpenAssetsApi.java
> +	private NetworkParameters getNetworkParameters(String network) {
Androidアプリを想定しており、設定ファイルからネットワークを切り替えることは無いので不要です。

2018-06-19 01:22 UTC, nakajo2011 requested changes

2018-06-19 01:22 UTC, nakajo2011 commented on src/main/java/com/chaintope/openassetsj/helper/OpenAssetsHelper.java
> +
このあたりの処理はUnspentOutputsクラスに持たせるべきな気がします。
あと、多分このコミットは作業途中のものと思うのですが、作業途中のものをcommitするとreviewが困難なので、一区切りついたものをあげてください。
なので３日で完成できるぐらい小さいタスクにしましょう。最初は３日でメソッド１つだけ実装する。ぐらいでも構いません。
それと実装とテストは必ずセットでコミットしてください。多分理想で言えば、１つのメソッドを実装した場合、正常ケースと異常ケースの２つ以上のテストを作成する必要があります。

また、ソースを変更する場合は変更理由も記述してください。新しい機能を実装する場合はどういった機能かという説明だけで問題ないです。

2018-07-03 05:28 UTC, nakajo2011 commented
変更内容が煩雑になりすぎてるので、このpull requestは一旦閉じます。
purabさんのリポジトリでも実装機能単位でbranchを切ってください。

2018-07-03 05:28 UTC, closed without merging